version: '3'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  nestjs:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
      DATABASE_CONNECTION: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: api
      JWT_SECRET: secret
      JWT_EXPIRES_IN: 3d



volumes:
  mysql:
